[web]
development = true
address = "127.0.0.1"
port = 3001
ports = [17091]
loginUrl = "growserver.app"
cdnUrl = "growserver-cache.netlify.app"

[web.maintenance]
enable = false
message = "Maintenance Woi"

[web.tls]
key = "./assets/ssl/server.key"
cert = "./assets/ssl/server.crt"

[server]
bypassVersionCheck = true
logLevel = "info"